# Generated by Django 4.2.5 on 2023-09-19 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('name_surname', models.CharField(choices=[('JP', 'Jordan Price'), ('IA', 'Ian Alvarez'), ('WC', 'Wallace Castillo'), ('KS', 'Ken Sanders'), ('BP', 'Bob Patel'), ('JM', 'Jaime Myers'), ('EL', 'Ella Long'), ('SR', 'Stacey Ross'), ('WF', 'Wilma Foster'), ('GJ', 'Gina Jimenez')], default='JP', max_length=2, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200)),
                ('article_text', models.CharField(max_length=8000)),
                ('image', models.ImageField(upload_to='images/')),
                ('topic', models.CharField(default='economy', max_length=100)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsapp.author')),
            ],
        ),
    ]
