# Generated by Django 4.2.5 on 2023-10-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(choices=[('politics', 'politics'), ('business', 'business'), ('economy', 'economy'), ('world', 'world'), ('opinion', 'opinion'), ('health', 'health'), ('entertainment', 'entertainment'), ('lifestyle', 'lifestyle'), ('travel', 'travel'), ('sports', 'sports')], max_length=100, primary_key=True, serialize=False),
        ),
    ]
