# Generated by Django 4.2.5 on 2023-09-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_author_image_alter_article_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name_surname',
            field=models.CharField(choices=[('Bob Patel', 'Bob'), ('Ella Long', 'Ella'), ('Gina Jimenez', 'Gina'), ('Ian Alvarez', 'Ian'), ('Jaime Myers', 'Jaime'), ('Jordan Price', 'Jordan'), ('Ken Sanders', 'Ken'), ('Stacey Ross', 'Stacey'), ('Wallace Castillo', 'Wallace'), ('Wilma Foster', 'Wilma')], default='Jordan Price', max_length=100, primary_key=True, serialize=False),
        ),
    ]
